name: nest-rbac-module
on:
   push:
      tags:
         - '*'
jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
         attestations: write
         id-token: write
      steps:
         - name: Checkout from repo
           uses: actions/checkout@v4


         - name: Install dependencies
           run: npm install
           env:
              NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
 

         - name: Set release version
           run: npm version "${GITHUB_REF_NAME#v}" --no-git-tag-version

         - name: Build package
           run: npm run build

         - name: publish to registry
           uses: actions/setup-node@v4
           with:
              node-version: 20
              registry-url: "https://npm.pkg.github.com"
              scope: "@twistedlogixph"

         - run: npm publish
           env:
              NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
