name: nest-rbac-module
on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
         attestations: write
         id-token: write
      steps:
         - name: Checkout from repo
           uses: actions/checkout@v4

         - name: publish to registry
           uses: actions/setup-node@v4
           with:
              node-version: 20
              registry-url: "https://npm.pkg.github.com"
              scope: "@twistedlogixph"

         - name: Install dependencies
           run: npm install
           env:
              NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

         - run: npm publish
           env:
              NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
